apiVersion: v1
kind: Secret
metadata:
  name: xpense-backend-secret
  namespace: xpense
type: Opaque
data:
  TRACKER_DATASOURCE_USERNAME: eHBlbnNlX2FkbWlu
  TRACKER_DATASOURCE_PASSWORD: eHBlbnNlVHJhY2tlcjEyMzQ=
  MF_DATASOURCE_USERNAME: eHBlbnNlX2FkbWlu
  MF_DATASOURCE_PASSWORD: eHBlbnNlVHJhY2tlcjEyMzQ=