apiVersion: apps/v1
kind: Deployment
metadata:
  name: xpense-tracker-frontend
  namespace: xpense
spec:
  replicas: 1
  selector:
    matchLabels:
      app: xpense-tracker-frontend
  template:
    metadata:
      labels:
        app: xpense-tracker-frontend
    spec:
      containers:
        - name: xpense-tracker-frontend
          image: ghcr.io/emil-ep/xpense-ui:latest
          ports:
            - containerPort: 80
          volumeMounts:
            - name: nginx-config
              mountPath: /etc/nginx/conf.d/default.conf
              subPath: default.conf
      volumes:
        - name: nginx-config
          configMap:
            name: frontend-nginx-config