apiVersion: v1
kind: Service
metadata:
  name: xpense-tracker-backend
  namespace: xpense
spec:
  selector:
    app: xpense-tracker-backend
  ports:
    - port: 8085
      targetPort: 8085
  type: ClusterIP