apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: xpense
type: Opaque
stringData:
  POSTGRES_USER: xpense_admin
  POSTGRES_PASSWORD: xpenseTracker1234
  POSTGRES_DB: xpense_tracker