apiVersion: v1
kind: ConfigMap
metadata:
  name: xpense-consumer-config
  namespace: xpense
data:
  MF_DATASOURCE_URL: "jdbc:postgresql://postgres:5432/mf"
  KAFKA_BOOTSTRAP_SERVER: "kafka:9092"
  LOGGING_LEVEL_ROOT: "INFO"
